/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteGalleryRouteImport } from './routes/_site.gallery'
import { Route as SiteServicesRouteImport } from './routes/_site.services'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteGalleryRoute = SiteGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicesRoute = SiteServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/gallery': typeof SiteGalleryRoute
  '/services': typeof SiteServicesRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/gallery': typeof SiteGalleryRoute
  '/services': typeof SiteServicesRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/gallery': typeof SiteGalleryRoute
  '/_site/services': typeof SiteServicesRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/admin' | '/auth' | '/about' | '/contact' | '/gallery' | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/admin' | '/auth' | '/about' | '/contact' | '/gallery' | '/services' | '/'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/auth'
    | '/_site/about'
    | '/_site/contact'
    | '/_site/gallery'
    | '/_site/services'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/gallery': {
      id: '/_site/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof SiteGalleryRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/services': {
      id: '/_site/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof SiteServicesRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteGalleryRoute: typeof SiteGalleryRoute
  SiteServicesRoute: typeof SiteServicesRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteGalleryRoute: SiteGalleryRoute,
  SiteServicesRoute: SiteServicesRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
